### ISSUE TITLE
Failed to decode downloaded font (Chrome)

### ISSUE THREAD

**Issue by debnet** [taigaio/taiga-front-dist#9]
Failed to decode downloaded font: http://scrum.www.fr/v-1451994977764/fonts/Opensans-Regular.ttf

Thanks.

**Comment by Xaviju** [comment]
Please can you give us a little more information about the problem? 
What is happening exactly? Which browser ? How can we reproduce it?

Thanks

**Comment by debnet** [comment]
Hi @Xaviju,

Problem appears since update to last version of dist, the front is unable to retrieve the font due to the error above. The message came from Chrome debug log. In order to reproduce, you just have to browser on any page.

![bug](https://cloud.githubusercontent.com/assets/634832/12444800/e9a9d5e4-bf60-11e5-87f3-d5e3309d3d0f.png)

Thanks.

**Comment by Xaviju** [comment]
Thanks @debnet 
I cannot reproduce it on production with Chrome or Firefox
- is this error happening in tree.taiga.io or on your own instance? Can you test if this is happening also in tree.taiga.io?

**Comment by fuentes010** [comment]
Hi I've just update my own instance to the last stable version and I'm getting the same error.

<img width="1267" alt="captura de pantalla 2016-01-20 a las 13 49 18" src="https://cloud.githubusercontent.com/assets/4355395/12449361/fa3722b0-bf7c-11e5-9865-90ab5eca0b53.png">

**Comment by Xaviju** [comment]
@fuentes010 @debnet 
We are testing it internally and we cannot reproduce it (Chrome and Firefox), but we had a bug related to fonts in the latest release with some browsers. That could be the problem.

It would be helpful to know what browser versions are you using to reproduce a similar environment.
Please check if it is happening in tree.taiga.io as well with Chrome and Firefox if possible.

Otherwise, we will fix this font issue in our next release (probably next week).

**Comment by fuentes010** [comment]
@Xaviju 
Ok, great! I'm using Chrome version 47.0.2526.111 (64-bit)
I've logged in to tree.taiga.io and there isn't any error 😁

**Comment by fuentes010** [comment]
@Xaviju 
I've just update to the last stable version and there isn't any error, so I think that the bug is already fixed.
You guys are doing a great work! 💪
Thank's!

**Comment by bameda** [comment]
Good. Thanks to you for using Taiga
